---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: application-alert-rules
  namespace: monitoring

  labels:
    release: prometheus

spec:

  groups:

    - name: kubernetes-alerts

      rules:

        # Pod CrashLoopBackOff
        - alert: PodCrashLooping

          expr: |
            rate(kube_pod_container_status_restarts_total[5m]) > 0

          for: 5m

          labels:
            severity: critical

          annotations:
            summary: "Pod is restarting repeatedly"
            description: |
              Pod {{ $labels.pod }}
              in namespace {{ $labels.namespace }}
              is restarting frequently.


        # Pod Not Ready
        - alert: PodNotReady

          expr: |
            kube_pod_status_ready{condition="false"} == 1

          for: 10m

          labels:
            severity: warning

          annotations:
            summary: "Pod is not ready"
            description: |
              Pod {{ $labels.pod }}
              in namespace {{ $labels.namespace }}
              has been unhealthy for more than 10 minutes.


        # High CPU Usage
        - alert: HighCPUUsage

          expr: |
            100 -
            (avg by(instance)
            (rate(node_cpu_seconds_total{
            mode="idle"
            }[5m])) * 100)
            > 85

          for: 10m

          labels:
            severity: warning

          annotations:
            summary: "High CPU usage detected"
            description: |
              CPU usage on {{ $labels.instance }}
              is above 85%.


        # High Memory Usage
        - alert: HighMemoryUsage

          expr: |
            (
              node_memory_MemAvailable_bytes
              /
              node_memory_MemTotal_bytes
            ) < 0.15

          for: 10m

          labels:
            severity: warning

          annotations:
            summary: "High memory usage"
            description: |
              Available memory is below 15%
              on {{ $labels.instance }}.


        # Node Down
        - alert: NodeDown

          expr: |
            up{job="node-exporter"} == 0

          for: 5m

          labels:
            severity: critical

          annotations:
            summary: "Node is unreachable"
            description: |
              Kubernetes node {{ $labels.instance }}
              is down.


        # API Server Down
        - alert: KubernetesAPIServerDown

          expr: |
            up{job="apiserver"} == 0

          for: 5m

          labels:
            severity: critical

          annotations:
            summary: "Kubernetes API server unavailable"
            