---
apiVersion: v1
kind: Secret

metadata:
  name: alertmanager-secret
  namespace: monitoring

type: Opaque

stringData:
  smtp-password: "CHANGE_ME"
  slack-webhook-url: "https://hooks.slack.com/services/CHANGE/ME"
