---
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}

type: Opaque

stringData:
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
{{- end }}
