---
{{- if .Values.secret.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}

type: Opaque

stringData:
  API_KEY: {{ .Values.secret.apiKey | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}

{{- end }}
