---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}

data:
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}

  # Database Configuration
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}

  # AWS Region
  AWS_REGION: {{ .Values.config.AWS_REGION | quote }}

  # Logging
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}

  # Observability
  PROMETHEUS_URL: {{ .Values.config.PROMETHEUS_URL | quote }}
  ALERTMANAGER_URL: {{ .Values.config.ALERTMANAGER_URL | quote }}
  GRAFANA_URL: {{ .Values.config.GRAFANA_URL | quote }}
  LOKI_URL: {{ .Values.config.LOKI_URL | quote }}
