---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: postgres-service-monitor
  namespace: monitoring

  labels:
    release: prometheus

spec:
  # Select postgres-exporter service
  selector:
    matchLabels:
      app: postgres-exporter

  # PostgreSQL exporter namespace
  namespaceSelector:
    matchNames:
      - database

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
