---
apiVersion: 1

datasources:

  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy

    url: http://prometheus-operated.monitoring.svc.cluster.local:9090

    isDefault: true

    editable: false

    jsonData:
      timeInterval: 30s


  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy

    url: http://loki.monitoring.svc.cluster.local:3100

    editable: false


  # PostgreSQL datasource
  - name: PostgreSQL
    type: postgres
    access: proxy

    url: postgres.database.svc.cluster.local:5432

    database: applicationdb

    user: grafana

    editable: false

    jsonData:
      postgresVersion: 1500
      sslmode: disable
      