# Number of PostgreSQL replicas
# For production with StatefulSet, keep this as 1 unless using PostgreSQL replication.
replicaCount: 1

image:
  repository: postgres
  tag: "16.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: "1"
    memory: 1Gi

config:
  POSTGRES_DB: appdb
  PGDATA: /var/lib/postgresql/data/pgdata

secret:
  enabled: true

  postgresUser: appuser
  postgresPassword: change-me

persistence:
  enabled: true

  storageClass: gp3
  accessMode: ReadWriteOnce
  size: 20Gi

serviceAccount:
  create: true
  name: ""
  automount: false

  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Enable this if you're using a StatefulSet
statefulset:
  enabled: true
